function init(self)
    msg.post(".", "acquire_input_focus")
    self.game_over = false
    gui.set_enabled(gui.get_node("game_over_bg"), false)
   
    local play_again_btn = gui.get_node("play_again")
    gui.set_enabled(play_again_btn, false)
   
end

function on_message(self, message_id, message, sender)
    if message_id == hash("update_hp_bar") then
        
        local bar = gui.get_node("health")
        local hp_percentage = message.hp / message.HP_MAX
        gui.set_scale(bar, vmath.vector3(hp_percentage, 1, 1))
        --print(hp_percentage)
        --gui.set_text(gui.get_node("health_text"), "HP: " .. message.hp
        
        --gui.set_text(gui.get_node("lives_text"), "Lives: " .. message.lives)
        --gui.set_text(gui.get_node("score_text"), "Score: " .. message.score)
    elseif message_id == hash("game_over") then
        self.game_over = true
        --gui.set_alpha(gui.get_node("game_over_text"), 1.0)
        --gui.set_alpha(gui.get_node("restart_button"), 0.8)
        --gui.set_alpha(gui.get_node("restart_text"), 1.0)
        --gui.set_enabled(gui.get_node("restart_button"), true)
        print("[hud.gui_script]msg comes from player: Game Over!")
        gui.set_enabled(gui.get_node("game_over_bg"), true)
        msg.post("/Orcs#OrcsFactory", "stop_spawning")  -- zatrzymaj fabrykę orków
        gui.set_enabled(gui.get_node("play_again"), true)
    end

    if message_id == hash("update_points") then
        --gui.set_text(gui.get_node("text"), "Score: " .. message.score)
        gui.set_text(gui.get_node("text"), message.score)
    end


end

function on_input(self, action_id, action)
    
    --restart game - later reload proxy scollection should be created
    if self.game_over and gui.pick_node(gui.get_node("play_again"), action.x, action.y) then   
        if action_id == hash("touch") and action.pressed then
            --msg.post("/game#game", "restart")
            sys.reboot() --reset everything, including score and lives, by rebooting the game
            return true
        end
    end

    if self.game_over and action_id == hash("touch") and action.pressed then
        --msg.post("/game#game", "restart")
        return true
    end
    return false
end
