	function init(self)	
		self.ladder_enabled = false
		go.set("#ladder_sprite", "tint.w", 0.0)
		self.end_pos = go.get_position()  --pobierz pozysjepoczatkowa drabiny
		local start_y = self.end_pos.y - 50 -- ustaw startowa pozycje drabiny 100 pixeli nizej
		go.set_position(vmath.vector3(self.end_pos.x, start_y, self.end_pos.z)) -- przesun 100 pixeli
		--self.enabled = false

	end

	function on_message(self, message_id, message, sender)
		
		if message_id == hash("enable_ladder") and self.ladder_enabled == false then			
			
			-- RUCH CAŁEGO GO (".")  
			go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, self.end_pos.y,  go.EASING_OUTQUAD, 1, 0.0,
			function()
				self.ladder_enabled = true
			end)        

			-- Fade SPRITE (TINT)
			go.animate("#ladder_sprite", "tint.w", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_LINEAR, 0.5)		
			--go.set("#ladder_sprite", "tint.w", 1.0)
		end
	end

	