
local module = require('main.module')
local STATE_WALK_TO_POSITION = 1       
local STATE_CLIMBING = 2               
local STATE_ATTACK_WALL = 3
local STATE_FALL = 4      
local STATE_DIE = 5  


function init(self)
	
	
	self.state = STATE_WALK_TO_POSITION
	local index, point = module.get_free_point()
	module.set_taken(index, true)
	 if index == nil then
		pprint("No free point [DELETE] Orc")
	    go.delete() -- No free point, delete the Orc
		return
	end
	
	
	pprint("Orc initialized at point index: ".. tostring(index))
	local start_pos = go.get_position()
	local distance = math.abs(point.x - start_pos.x)
	local speed = 50 -- pixels per second
	local duration = distance / speed
	
	if point.x > start_pos.x then
		sprite.set_hflip("#sprite",true) -- Odbicie poziome w zależności od kierunku ruchu
	end
	--go.animate(url, property, playback, to, easing, duration, delay, complete_function)
	local delay =math.random()*0.3
	go.animate('.', 'position.x', go.PLAYBACK_ONCE_FORWARD, point.x, go.EASING_LINEAR, duration,delay,function ()
		
		pprint("Reached:".. tostring(index))
	end)	
	 	
end



function update(self, dt)
	--local velocity = go.get("#", "velocity") -- Twój sposób na pobranie prędkości lub innej zmiennej
	--sprite.set_hflip("#sprite",true) -- Odbicie poziome w zależności od kierunku ruchu
end

--1 Spawn
--2 idz do punktu
--3 drabina + wspinaj sie