local module = require('main.module')
-- kamiein wylaczac po spadaniu i hit w orkva?
function init(self)
	self.spawn_interval = 2  -- co 1sekundy
	self.spawn_positions = { vmath.vector3(555, 53, 0),vmath.vector3(-100, 53, 0)}
	
	timer.delay(self.spawn_interval, true, 
	
	function()
		local index_position = math.random(1, #self.spawn_positions)
		local spawn_pos = self.spawn_positions[index_position]
		
		local index, point = module.get_free_point()
		if index ~= nil then
			print( "points:"..index.." create Orc")
			local orc_id = factory.create("#orc_factory", spawn_pos)
		end
	
	end)


	
end
 
 