local module = require('main.module')
-- kamiein wylaczac po spadaniu i hit w orkva?
function init(self)
	orc = 0
	self.spawn_interval = 0.5  -- co 1sekundy
	self.spawn_positions = { vmath.vector3(555, 53, 0),vmath.vector3(-100, 53, 0)}
	
	timer.delay(self.spawn_interval, true, 
	
	function()
		local index_position = math.random(1, #self.spawn_positions)
		local spawn_pos = self.spawn_positions[index_position]
		
		
		
		local index, point = module.get_free_point()
		if index ~= nil then
			--print( "points:"..index.." create Orc")
			module.set_taken(index, true) -- zaznacz punkt jako zajety ale #
			
			--jak orc umrze to zwolnij punkt w orcu chyba 
			local orc_id = factory.create("#orc_factory", spawn_pos, nil, {target_point=point, index_ladder=index}) -- przekazanie punktu docelowego do orka
			orc = orc +1
			--print("[OrcFact]"..tostring(orc_id).." - init_orc:"..orc)

		end
	
	end)


	
end
 
	