function init(self)
	self.falling = false
	self.fall_speed = 300
	self.stone_pos = go.get_position()
	--pprint("Stone pos="..self.stone_pos)
end

 

function update(self, dt)
	if self.falling then
		self.stone_pos = go.get_position()
		self.stone_pos.y = self.stone_pos.y - self.fall_speed * dt
		--self.stone_pos.z=0
		go.set_position(self.stone_pos)
		
			

		if self.stone_pos.y <=-10 then go.delete(go.get_id(), true) 	end
	
	end

	 	
		 
end

function on_message(self, message_id, message, sender)
	if message_id == hash("stone_start_falling") then			
		self.falling = true		
	end

	if message_id == hash("collision_response") then
		if message.other_group == hash("orc")  then
			msg.post(message.other_id,hash("orc_hitted_by_stone"),{stone_speed=self.fall_speed})
			msg.post("#collisionobject", "disable") --collision disable for stone
			--print("[stone]msg send to:"..message.other_id)	
		end
	end
end
